version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: psycho-bot
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=
      - SPRING_DATASOURCE_USERNAME=
      - SPRING_DATASOURCE_PASSWORD=
      - BOT_TOKEN=
      - BOT_ADMIN_PASSWORD=
    networks:
      - psycho-network

  postgres_db:
    image: postgres:17.4
    container_name: postgres_db
    environment:
      - POSTGRES_DB=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - psycho-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d mydb" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:9.1
    container_name: psycho-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=
      - PGADMIN_DEFAULT_PASSWORD=
    ports:
      - "80:80"
    depends_on:
      - postgres_db
    networks:
      - psycho-network

volumes:
  postgres_data:

networks:
  psycho-network:
    driver: bridge 